dist: xenial

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update && sudo apt-get install -y libsodium18 libsodium-dev

before_script:
  - cmake .

script: make && make test ARGS="-V"
