dist: xenial

addons:
  coverity_scan:
    project:
      name: "pb173-2019/hello-world"
      description: "Hello world"
    notification_email: adam.ivora@gmail.com
    build_command_prepend: "cmake ."
    build_command: "make"
    branch_pattern: coverity_scan

language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update
  - sudo apt-get install libqt5websockets5-dev
  - cmake .

script: make && make test ARGS="-V"
