version: "{build}"

image: ubuntu

init:
  - git config --global core.autocrlf input

install:
  - git submodule update --init --recursive
  - sudo apt-get update && sudo apt-get install -y libsodium18 libsodium-dev

build_script:
  - cmake .
  - make

test_script:
   - make test ARGS="-V"

