version: "{build}"

os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.11.0\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"


before_build:
  - set Path=C:\Qt\5.6\msvc2015_64\bin;%Path%
  - cmake -H. -BBuild -G "Visual Studio 15 2017 Win64" .

# build with MSBuild
build:
  project: Build\helloworld.sln
  parallel: true
  verbosity: normal

test_script:
  - cd Build
  #- ctest -V -j 2 -C %CONFIGURATION%
